Repository LabExT/LabExT, pull requests merged in 2021-11, with the labels that each got.

#14 README: Add testing instructions
  README.md
  docs/installation.md
  docs/setup_dev_env.md
  mkdocs.yml
Labels: documentation

#11 [Movement] Refactor: Introduce Stage interface and SmarAct implementation
  LabExT/Movement/Stage.py
  LabExT/Movement/Stage3DSmarAct.py
  LabExT/Tests/Movement/Stage3DSmarAct/Base_test.py
  LabExT/Tests/Movement/Stage3DSmarAct/Channel_test.py
  LabExT/Tests/Movement/Stage3DSmarAct/SmarActTestCase.py
  LabExT/Tests/Movement/Stage3DSmarAct/__init__.py
  LabExT/Tests/Movement/__init__.py
Labels: Refactoring

#16 [Movement] Stop method for SmarAct stages
  LabExT/Movement/Stage3DSmarAct.py
  LabExT/Tests/Movement/Stage3DSmarAct/Channel_test.py
Labels: enhancement

#18 Feature: Limit y-axis scaling in live viewer
  LabExT/View/Controls/PlotControl.py
  LabExT/View/LiveViewer/LiveViewerController.py
  LabExT/View/LiveViewer/LiveViewerModel.py
  LabExT/View/LiveViewer/LiveViewerView.py
Labels: enhancement
